nameservers:
    - 172.16.128.30
    - 172.16.128.31
    - 172.16.128.34
dnsdomain: 'produxi.net'
krbclient::realm: 'PRODUXI.NET'
ldapclient::server: 'molybdenum.produxi.net'
ldapclient::basedn: 'dc=produxi,dc=net'
ldapclient::nss_min_uid: '500'
ldapclient::nss_max_uid: '100000'
ldapclient::nss_user_attr: 'uidNumber'
ldapclient::nss_group_attr: 'primaryGroupID'
